name: Terraform Kong Platform Ops

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      run_remove:
        description: "Run Terraform Destroy instead of Apply?"
        required: true
        default: "false"
        type: choice
        options:
          - "true"
          - "false"

env:
  TF_LOG: INFO
  TF_VAR_system_account_access_token: ${{ secrets.KONNECT_SPAT }}
  TF_VAR_server_url: "https://us.api.konghq.com"
  TF_VAR_environment: "production"

jobs:
  destroy:
    name: Terraform Destroy
    if: ${{ github.event.inputs.run_remove == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init

      - name: Terraform Plan
        working-directory: ./terraform
        run: terraform plan -input=false

      - name: Terraform Destroy
        working-directory: ./terraform
        run: terraform destroy -auto-approve -input=false
        env:
          KONNECT_PAT: ${{ secrets.KONNECT_PAT }}

  terraform:
    if: ${{ github.event.inputs.run_remove != 'true' }}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: latest

    - name: Terraform Init
      working-directory: ./terraform
      run: terraform init

    - name: Terraform Validate
      working-directory: ./terraform
      run: terraform validate

    - name: Terraform Plan
      working-directory: ./terraform
      run: terraform plan -input=false

    - name: Terraform Apply
      if: github.ref == 'refs/heads/main'
      working-directory: ./terraform
      run: terraform apply -auto-approve -input=false
      env:
        KONNECT_PAT: ${{ secrets.KONNECT_PAT }}
